name: CI/CD Pipeline for IIS

on:
  push:
    branches:
      - demo  # Change to your desired branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Angular CLI
      run: npm install -g @angular/cli@18

    - name: Install deps and build angular app
      run: |
          cd clientApp
          npm install
          ng build

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Adjust for your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive the build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./publish

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        
    - name: Deploy to IIS using Web Deploy
      run: |
        msdeploy.exe -verb:sync `
          -source:contentPath="C:\github-runner\actions-runner\_work\E-Commerce-Angular\publish" `
          -dest:contentPath="\\Agile-Tech02\c$\inetpub\wwwroot\ecommerce-skinet",computerName="https://Agile-Tech02:8172/msdeploy.axd",userName="Administator",password="Zsoxfsq977#@",authType="basic" `
          -allowUntrusted -enableRule:AppOffline
env:
  DOTNET_ROOT: C:\Program Files\dotnet
