name: CI/CD Pipeline for IIS

on:
  push:
    branches:
      - demo  # Change to your desired branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install deps and build angular app
      run: |
          cd clientApp
          npm install
          ng build

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive the build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./publish

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Set up PowerShell remoting
      shell: pwsh
      run: |
          $username = "AzureAD\MaheshMadai"
          $password = "200014" | ConvertTo-SecureString -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($username, $password)
          $session = New-PSSession -ComputerName "Agile-Tech02" -Credential $cred
    
          # Stop the IIS App Pool
          Invoke-Command -Session $session -ScriptBlock {
            Import-Module WebAdministration
            Stop-WebAppPool -Name "ecommerce-skinet"
          }
    
          # Copy files from GitHub Actions runner to IIS server
          Copy-Item -Path ./publish/* -Destination "\\Agile-Tech02\c$\inetpub\wwwroot\ecommerce-skinet" -Recurse -Force -ToSession $session

          # Start the IIS App Pool
          Invoke-Command -Session $session -ScriptBlock {
          Import-Module WebAdministration
          Start-WebAppPool -Name "ecommerce-skinet"
          }

          # Clean up session
          Remove-PSSession $session
env:
  DOTNET_ROOT: C:\Program Files\dotnet
